### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [candrian/LogitechZ623#1]
Hello!

I found link to this project from https://hackaday.com/2020/12/07/an-epic-quest-for-a-motorized-volume-knob/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and STL-files in any purpose?
It would be great to see any popular open source license.

**Comment by candrian** [comment]
Hi and thanks for the note. I just added the license. Feel free to contribute

**Comment by vazhnov** [comment]
GPL v3.0 — great! Thank you!
